### ISSUE TITLE
Safari browser: Broken image links.

### ISSUE THREAD

**Issue by lemmih** [daef/poly-bool-comparison#3]
Hi. The result image links are broken.

For example, one of them looks like this: https://daef.github.io/poly-bool-comparison/magick///daef.github.io/poly-bool-comparison/rust-geo-booleanop/pngs/twointersectingcontours_tri3_X.png
But it should probably be: https://daef.github.io/poly-bool-comparison/rust-geo-booleanop/pngs/twointersectingcontours_tri3_X.png

**Comment by daef** [comment]
where did you find the broken links?
the [overview](https://daef.github.io/poly-bool-comparison/dissection/) seems to work for me :/

**Comment by lemmih** [comment]
Oh, now it works for me as well. Not sure what happened.
I originally followed the link from here: https://github.com/21re/rust-geo-booleanop/issues/14

**Comment by lemmih** [comment]
Ah, I can reproduce it. It works in Firefox but fails in Safari.

**Comment by daef** [comment]
I guess I can slap a 'Safari not supported' label on the front...

**Comment by lemmih** [comment]
Alright.

**Comment by daef** [comment]
I'd be happy to merge a fix, but I'm not planning to install/use Safari
