### ISSUE TITLE
please include skia pathKit 

### ISSUE THREAD

**Issue by martin19** [daef/poly-bool-comparison#4]
Thank you for your project, I think its a very good way of benchmarking the algorithms.
There is a wasm version of skia's path algorithms (https://skia.org/docs/user/modules/pathkit/) 
which includes boolean operations. 
I think it would be very interesting to see how the leading 2d library performs in this test.
I could try to implement this, but if you would want to include it I think you would be more efficient in doing this.
Please let me know what you think.

**Comment by martin19** [comment]
I've included pathkit in your test. Feel free to merge these changes if you're interested.
https://github.com/martin19/poly-bool-comparison

**Comment by daef** [comment]
Sorry for the delay, I'm pretty busy atm :/

Happy to merge :+1:

**Comment by daef** [comment]
huh - there's no PR...
